# Generated by Django 3.0.7 on 2020-06-22 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userface', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
