# Generated by Django 3.0.7 on 2020-06-25 06:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userface', '0003_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='filename',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='filename',
            unique_together={('username', 'filename')},
        ),
    ]
