# Generated by Django 3.0.7 on 2020-06-25 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userface', '0004_auto_20200625_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='filename',
            name='record_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filename',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
